# Generated by Django 5.2.3 on 2025-07-03 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='transfer_time_minutes',
        ),
    ]
