# Generated by Django 5.2.3 on 2025-07-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_remove_tour_distance_km_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_confirmed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='requested_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='started_at',
        ),
    ]
